CREATE DATABASE musica;

USE MUSICA;

CREATE TABLE USUARIO(
	ID_USUARIO INT AUTO_INCREMENT,
    USUARIO		VARCHAR(50) NOT NULL,
    SENHA		VARCHAR(256) NOT NULL,
    CONSTRAINT PK_USU_ID_USUARIO PRIMARY KEY(ID_USUARIO),
    CONSTRAINT UN_USU_USUARIO UNIQUE(USUARIO)
);

ALTER TABLE USUARIO
	ADD COLUMN DT_INSERT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN DT_UPDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE LOG(
	ID_LOG	INT AUTO_INCREMENT,
    ID_USUARIO	INT NOT NULL DEFAULT 1,
    DT_INSERT DATETIME NOT NULL DEFAULT current_timestamp,
    OPERACAO VARCHAR(500) NOT NULL,
    CONSTRAINT PK_LOG_ID_LOG PRIMARY KEY(ID_LOG),
    CONSTRAINT FK_LOG_ID_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
    
CREATE TABLE USUARIO_HAS_LOG(
	ID_USUARIO INT NOT NULL,
    ID_LOG		INT NOT NULL,
    CONSTRAINT FK_USU_HAS_ID_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_USU_HAS_ID_LOG FOREIGN KEY(ID_LOG) REFERENCES LOG(ID_LOG)
); 

CREATE TABLE ESTUDANTE(
	ID_ESTUDANTE	INT AUTO_INCREMENT,
    NOME			VARCHAR(500) NOT NULL,
    DT_NASCIMENTO	DATE NOT NULL,
    ID_USUARIO		INT,
    DT_INSERT 		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT EST_ID_ESTUDANTE PRIMARY KEY(ID_ESTUDANTE,NOME,DT_NASCIMENTO),
    CONSTRAINT FK_EST_ID_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CONTATO_ESTUDANTE(
	ID_ESTUDANTE		INT NOT NULL,
    NUMERO_RESPONSAVEL	VARCHAR(11) NOT NULL,
    CONSTRAINT PK_CON_ID_ESTUDANTE PRIMARY KEY(ID_ESTUDANTE, NUMERO_RESPONSAVEL),
    CONSTRAINT FK_CON_EST_ID_ESTUDANTE FOREIGN KEY(ID_ESTUDANTE) REFERENCES ESTUDANTE(ID_ESTUDANTE)
);

ALTER TABLE CONTATO_ESTUDANTE
	ADD COLUMN DT_INSERT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN DT_UPDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
    
CREATE TABLE RESPONSAVEL(
	ID_RESPONSAVEL INT AUTO_INCREMENT,
    NOME_RESPONSAVEL VARCHAR(500) NOT NULL,
    DT_NASCIMENTO	DATE NOT NULL,
    RG_RESPONSAVEL	VARCHAR(11),
    EMAIL_RESPONSAVEL VARCHAR(500),
    CONSTRAINT PK_RES_ID_RESPONSAVEL PRIMARY KEY(ID_RESPONSAVEL, NOME_RESPONSAVEL, DT_NASCIMENTO)
);

ALTER TABLE RESPONSAVEL
	ADD COLUMN DT_INSERT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN DT_UPDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
    
USE musica;

CREATE USER "musico"@"localhost" IDENTIFIED BY "mudar@123";

GRANT SELECT, UPDATE, INSERT ON musica.* TO "musico"@"localhost";

